import { Language } from './translations';

export const DASHBOARD_TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: { speed: 'Speed', base: 'Base', coresLogic: 'Cores/Logic', l3Cache: 'L3 Cache', virt: 'Virt', uptime: 'Up time', physicalMemory: 'Physical Memory', inUse: 'In use', available: 'Available', slots: 'Slots', cached: 'Cached', vramUsage: 'VRAM Usage', driverVer: 'Driver Ver', driverDate: 'Driver Date', directx: 'DirectX', connection: 'Connection', ipv4: 'IPv4', ipv6: 'IPv6' },
  ru: { speed: 'Скорость', base: 'Базовая', coresLogic: 'Ядра/Потоки', l3Cache: 'Кэш L3', virt: 'Виртуализация', uptime: 'Время работы', physicalMemory: 'Физ. память', inUse: 'Используется', available: 'Доступно', slots: 'Гнезда', cached: 'Кэшировано', vramUsage: 'Использование VRAM', driverVer: 'Версия драйвера', driverDate: 'Дата драйвера', directx: 'DirectX', connection: 'Подключение', ipv4: 'IPv4', ipv6: 'IPv6' },
  zh: { speed: '速度', base: '基础', coresLogic: '核心/逻辑', l3Cache: 'L3缓存', virt: '虚拟化', uptime: '运行时间', physicalMemory: '物理内存', inUse: '已用', available: '可用', slots: '插槽', cached: '已缓存', vramUsage: '显存使用', driverVer: '驱动版本', driverDate: '驱动日期', directx: 'DirectX', connection: '连接', ipv4: 'IPv4', ipv6: 'IPv6' },
  es: { speed: 'Velocidad', base: 'Base', coresLogic: 'Núcleos/Lógicos', l3Cache: 'Caché L3', virt: 'Virt', uptime: 'Tiempo activo', physicalMemory: 'Memoria Física', inUse: 'En uso', available: 'Disponible', slots: 'Ranuras', cached: 'En caché', vramUsage: 'Uso VRAM', driverVer: 'Ver Controlador', driverDate: 'Fecha Controlador', directx: 'DirectX', connection: 'Conexión', ipv4: 'IPv4', ipv6: 'IPv6' },
  de: { speed: 'Geschw.', base: 'Basis', coresLogic: 'Kerne/Logik', l3Cache: 'L3 Cache', virt: 'Virt', uptime: 'Laufzeit', physicalMemory: 'Physischer Speicher', inUse: 'In Nutzung', available: 'Verfügbar', slots: 'Steckplätze', cached: 'Zwischengesp.', vramUsage: 'VRAM-Nutzung', driverVer: 'Treiber Ver', driverDate: 'Treiber Datum', directx: 'DirectX', connection: 'Verbindung', ipv4: 'IPv4', ipv6: 'IPv6' },
  ja: { speed: '速度', base: 'ベース', coresLogic: 'コア/論理', l3Cache: 'L3キャッシュ', virt: '仮想化', uptime: '稼働時間', physicalMemory: '物理メモリ', inUse: '使用中', available: '利用可能', slots: 'スロット', cached: 'キャッシュ済', vramUsage: 'VRAM使用量', driverVer: 'ドライバーVer', driverDate: 'ドライバー日付', directx: 'DirectX', connection: '接続', ipv4: 'IPv4', ipv6: 'IPv6' },
  pt: { speed: 'Velocidade', base: 'Base', coresLogic: 'Núcleos/Lógicos', l3Cache: 'Cache L3', virt: 'Virt', uptime: 'Tempo ativo', physicalMemory: 'Memória Física', inUse: 'Em uso', available: 'Disponível', slots: 'Slots', cached: 'Em cache', vramUsage: 'Uso de VRAM', driverVer: 'Ver Driver', driverDate: 'Data Driver', directx: 'DirectX', connection: 'Conexão', ipv4: 'IPv4', ipv6: 'IPv6' },
  bn: { speed: 'গতি', base: 'বেস', coresLogic: 'কোর/লজিক', l3Cache: 'L3 ক্যাশ', virt: 'ভার্চু', uptime: 'আপটাইম', physicalMemory: 'ফিজিক্যাল মেমোরি', inUse: 'ব্যবহৃত', available: 'উপলব্ধ', slots: 'স্লট', cached: 'ক্যাশেড', vramUsage: 'VRAM ব্যবহার', driverVer: 'ড্রাইভার ভার্সন', driverDate: 'ড্রাইভার তারিখ', directx: 'DirectX', connection: 'সংযোগ', ipv4: 'IPv4', ipv6: 'IPv6' },
  hi: { speed: 'गति', base: 'बेस', coresLogic: 'कोर/लॉजिक', l3Cache: 'L3 कैश', virt: 'वर्चुअलाइजेशन', uptime: 'अपटाइम', physicalMemory: 'फिजिकल मेमोरी', inUse: 'उपयोग में', available: 'उपलब्ध', slots: 'स्लॉट', cached: 'कैश्ड', vramUsage: 'VRAM उपयोग', driverVer: 'ड्राइवर संस्करण', driverDate: 'ड्राइवर दिनांक', directx: 'DirectX', connection: 'कनेक्शन', ipv4: 'IPv4', ipv6: 'IPv6' },
  it: { speed: 'Velocità', base: 'Base', coresLogic: 'Core/Logici', l3Cache: 'Cache L3', virt: 'Virt', uptime: 'Tempo di attività', physicalMemory: 'Memoria Fisica', inUse: 'In uso', available: 'Disponibile', slots: 'Slot', cached: 'Nella cache', vramUsage: 'Uso VRAM', driverVer: 'Ver Driver', driverDate: 'Data Driver', directx: 'DirectX', connection: 'Connessione', ipv4: 'IPv4', ipv6: 'IPv6' },
  sw: { speed: 'Kasi', base: 'Msingi', coresLogic: 'Cores/Logic', l3Cache: 'L3 Cache', virt: 'Virt', uptime: 'Muda wa kazi', physicalMemory: 'Kumbukumbu ya Kimwili', inUse: 'Inatumika', available: 'Inapatikana', slots: 'Nafasi', cached: 'Imehifadhiwa', vramUsage: 'Matumizi VRAM', driverVer: 'Toleo la Dereva', driverDate: 'Tarehe ya Dereva', directx: 'DirectX', connection: 'Uunganisho', ipv4: 'IPv4', ipv6: 'IPv6' },
  id: { speed: 'Kecepatan', base: 'Dasar', coresLogic: 'Core/Logika', l3Cache: 'Cache L3', virt: 'Virt', uptime: 'Waktu Aktif', physicalMemory: 'Memori Fisik', inUse: 'Digunakan', available: 'Tersedia', slots: 'Slot', cached: 'Di-cache', vramUsage: 'Penggunaan VRAM', driverVer: 'Versi Driver', driverDate: 'Tanggal Driver', directx: 'DirectX', connection: 'Koneksi', ipv4: 'IPv4', ipv6: 'IPv6' },
};
